<?php

/**
 * Tina4 — The Intelligent Native Application 4ramework
 * Copyright 2007 - current Tina4
 * License: MIT https://opensource.org/licenses/MIT
 *
 * Live Firebird regression for ORM::count() / recordExists().
 *
 * Firebird folds an unquoted column alias to UPPER CASE, so
 * `SELECT COUNT(*) as cnt` comes back keyed `CNT`. ORM::count() read
 * `$row['cnt']` (lower case) → always null → **count() returned 0 for every
 * Firebird table**, and recordExists() (used by save() to pick insert vs
 * update) had the same defect. Both now read the count case-insensitively via
 * array_change_key_case() — the same class of bug already fixed for the v2→v3
 * migration bookkeeping (see MigrationV3Test).
 *
 * NOT a mock — runs against a REAL Firebird via the Database facade, gated on
 * TINA4_TEST_FIREBIRD_URL (CI without a live Firebird no-ops), mirroring
 * MigrationV3Test / MySQLMSSQLLiveTest.
 */

use PHPUnit\Framework\TestCase;
use Tina4\Database\Database;
use Tina4\ORM;

class FbOrmCountWidget extends ORM
{
    public string $tableName = "t_orm_count_test";
    public string $primaryKey = "id";
    public $id;
    public $name;
}

class FirebirdOrmCountTest extends TestCase
{
    private ?Database $db = null;

    protected function setUp(): void
    {
        if (!function_exists('ibase_connect') && !function_exists('fbird_connect')) {
            $this->markTestSkipped('ext-interbase not installed');
        }
        $url = getenv('TINA4_TEST_FIREBIRD_URL');
        if (!$url) {
            $this->markTestSkipped('Set TINA4_TEST_FIREBIRD_URL to run the live Firebird ORM count() test (e.g. firebird://SYSDBA:masterkey@localhost:3050/path/to/test.fdb)');
        }

        $this->db = Database::create($url);
        ORM::bindDatabase($this->db);

        $this->db->execute(
            "recreate table t_orm_count_test (" .
            "id integer generated by default as identity primary key not null, " .
            "name varchar(50))"
        );
        $this->db->commit();
        foreach (["alpha", "beta", "gamma"] as $n) {
            $this->db->execute("insert into t_orm_count_test (name) values (?)", [$n]);
        }
        $this->db->commit();
    }

    protected function tearDown(): void
    {
        if ($this->db !== null) {
            try { $this->db->execute("drop table t_orm_count_test"); } catch (\Throwable) {}
        }
    }

    public function testCountReturnsRowTotalOnFirebird(): void
    {
        // Sanity: the rows really are committed (raw COUNT via the facade).
        $raw = array_change_key_case($this->db->fetchOne("select count(*) as c from t_orm_count_test"));
        $this->assertSame(3, (int)$raw['c']);

        // The regression: ORM count() must agree, not return 0.
        $this->assertSame(3, (new FbOrmCountWidget())->count());
    }

    public function testCountWithConditionOnFirebird(): void
    {
        $this->assertSame(1, (new FbOrmCountWidget())->count("name = ?", ["beta"]));
        $this->assertSame(0, (new FbOrmCountWidget())->count("name = ?", ["nope"]));
    }
}
