<?php

/**
 * Tina4 — The Intelligent Native Application 4ramework
 * Copyright 2007 - current Tina4
 * License: MIT https://opensource.org/licenses/MIT
 *
 * Live Firebird regression for ORM writes (#132, write side):
 *
 *  - save() INSERT into a `generated by default as identity` PK must BACK-FILL
 *    the model's generated id (RETURNING on Firebird, as for PostgreSQL).
 *  - delete() / save()-as-update must PERSIST and be visible on a subsequent read
 *    from the SAME connection. This is the reporter's core symptom: writes were
 *    fine but the adapter's default read path held a frozen SNAPSHOT, so a
 *    just-committed change read back stale. Fixed by running non-transactional
 *    statements in a READ COMMITTED transaction.
 *
 * NOT a mock — runs against a REAL Firebird via the Database facade, gated on
 * TINA4_TEST_FIREBIRD_URL. Mirrors FirebirdOrmCountTest / MigrationV3Test.
 */

use PHPUnit\Framework\TestCase;
use Tina4\Database\Database;
use Tina4\ORM;

class FbOrmWriteWidget extends ORM
{
    public string $tableName = "t_orm_write_test";
    public string $primaryKey = "id";
    public $id;
    public $name;
}

class FirebirdOrmWriteTest extends TestCase
{
    private ?Database $db = null;

    protected function setUp(): void
    {
        if (!function_exists('ibase_connect') && !function_exists('fbird_connect')) {
            $this->markTestSkipped('ext-interbase not installed');
        }
        $url = getenv('TINA4_TEST_FIREBIRD_URL');
        if (!$url) {
            $this->markTestSkipped('Set TINA4_TEST_FIREBIRD_URL to run the live Firebird ORM write test');
        }

        $this->db = Database::create($url);
        ORM::bindDatabase($this->db);

        $this->db->execute(
            "recreate table t_orm_write_test (" .
            "id integer generated by default as identity primary key not null, " .
            "name varchar(50))"
        );
        $this->db->commit();
    }

    protected function tearDown(): void
    {
        if ($this->db !== null) {
            try { $this->db->execute("drop table t_orm_write_test"); } catch (\Throwable) {}
            // Close so the next test gets a fresh connection: ext-interbase reuses
            // a cached link for identical connect args, and a prior test object's
            // live transaction on that link would deadlock the next setUp's
            // RECREATE ("update conflicts with concurrent update").
            try { $this->db->close(); } catch (\Throwable) {}
        }
    }

    private function rawCount(): int
    {
        $row = array_change_key_case($this->db->fetchOne("select count(*) as c from t_orm_write_test") ?? []);
        return (int)($row['c'] ?? 0);
    }

    private function nameOf(int $id): ?string
    {
        $row = $this->db->fetchOne("select name from t_orm_write_test where id = ?", [$id]);
        return $row === null ? null : (array_change_key_case($row)['name'] ?? null);
    }

    public function testSaveBackfillsGeneratedIdentity(): void
    {
        $a = new FbOrmWriteWidget();
        $a->name = "one";
        $this->assertNotFalse($a->save());
        $this->assertGreaterThan(0, (int)$a->id, "save() must back-fill the generated identity id");

        $b = new FbOrmWriteWidget();
        $b->name = "two";
        $this->assertNotFalse($b->save());
        $this->assertGreaterThan((int)$a->id, (int)$b->id, "each insert gets a distinct, increasing generated id");

        $this->assertSame("one", $this->nameOf((int)$a->id));
        $this->assertSame("two", $this->nameOf((int)$b->id));
    }

    public function testDeletePersistsAndReadsFresh(): void
    {
        foreach (["alpha", "beta", "gamma"] as $n) {
            $this->db->execute("insert into t_orm_write_test (name) values (?)", [$n]);
        }
        $this->db->commit();
        $this->assertSame(3, $this->rawCount());

        $w = new FbOrmWriteWidget();
        $w->load("name = ?", ["beta"]);
        $id = (int)$w->id;
        $this->assertNotFalse($w->delete());

        $this->assertSame(2, $this->rawCount(), "delete() must remove the row AND the re-read must see it gone");
        $this->assertNull($this->nameOf($id));
    }

    public function testUpdatePersistsAndReadsFresh(): void
    {
        $this->db->execute("insert into t_orm_write_test (name) values (?)", ["before"]);
        $this->db->commit();

        $w = new FbOrmWriteWidget();
        $w->load("name = ?", ["before"]);
        $id = (int)$w->id;
        $w->name = "after";
        $this->assertNotFalse($w->save());

        $this->assertSame("after", $this->nameOf($id), "the update must be visible on a fresh read from the same connection");
    }
}
