<?php

/**
 * Tina4 — The Intelligent Native Application 4ramework
 * Copyright 2007 - current Tina4
 * License: MIT https://opensource.org/licenses/MIT
 */

use PHPUnit\Framework\TestCase;
use Tina4\McpServer;
use Tina4\McpDevTools;
use Tina4\ErrorTracker;
use Tina4\Plan;
use Tina4\Queue;
use Tina4\Router;
use Tina4\Database\Database;

/**
 * Invoke-every-tool conformance test for the built-in dev-MCP toolkit.
 *
 * The prior MCP tool test only checked REGISTRATION (names present). That let 7
 * tools ship functionally broken — they self-caught into {error} or returned a
 * stub info-string, so a registration-only test stayed green. This test boots a
 * REAL throwaway app (real file SQLite DB, a real route, a real ORM model, a real
 * pending migration, real plans), builds the real dev-MCP server, enumerates
 * EVERY registered tool FROM THE REGISTRY (nothing hardcoded), and:
 *
 *   1. invokes each tool via callTool() and asserts NONE throws (catches the
 *      ArgumentCountError-class throwers if a self-catch is ever removed), AND
 *   2. asserts the 7 fixed tools return REAL success payloads — not a stub
 *      info-string and not an {error} envelope.
 *
 * No mocks: every dependency (SQLite, the queue file backend, the router, the
 * migration runner, the error store, the plan store) is the real thing.
 */
class McpDevToolsConformanceTest extends TestCase
{
    private string $appRoot = '';
    private string $oldCwd = '';
    private string $dbFile = '';

    /** @var array<string, string> env keys set for the run, restored in tearDown */
    private array $savedEnv = [];

    protected function setUp(): void
    {
        $this->oldCwd = getcwd() ?: '';
        $this->appRoot = sys_get_temp_dir() . '/tina4_mcp_conformance_' . uniqid('', true);
        $this->dbFile = $this->appRoot . '/app.db';

        foreach ([
            'src/orm', 'src/routes', 'src/templates', 'src/public',
            'migrations', 'plan', 'data/sessions', 'logs',
        ] as $dir) {
            @mkdir($this->appRoot . '/' . $dir, 0755, true);
        }

        $this->setEnv('TINA4_DATABASE_URL', 'sqlite:///' . $this->dbFile);
        $this->setEnv('TINA4_DEBUG', 'true');
        $this->setEnv('TINA4_MCP', 'true');
        $this->setEnv('TINA4_AUTO_MIGRATE', 'false');   // migration_run is what applies migrations here
        $this->setEnv('TINA4_QUEUE_BACKEND', 'file');   // deterministic, no external service

        // composer.json so deps_list / file_read have a real target.
        file_put_contents($this->appRoot . '/composer.json', json_encode([
            'name' => 'tina4/conformance-fixture',
            'require' => ['php' => '>=8.2'],
        ], JSON_PRETTY_PRINT));

        // A real ORM model (global namespace, filename == class) so orm_describe
        // has a model to describe. Distinctive name to avoid cross-test clashes.
        if (!class_exists('ConformanceWidget')) {
            file_put_contents($this->appRoot . '/src/orm/ConformanceWidget.php', <<<'PHP'
<?php
class ConformanceWidget extends \Tina4\ORM {
    public string $tableName = "widget";
    public string $primaryKey = "id";
}
PHP);
            require $this->appRoot . '/src/orm/ConformanceWidget.php';
        }

        // A route file target for file_patch (pre-created so file_patch works
        // regardless of loop order; file_write overwrites it in the same pass).
        file_put_contents(
            $this->appRoot . '/src/routes/probe_generated.php',
            "<?php\n// generated by probe\nreturn function () { return 'ok'; };\n"
        );

        // A real, pending migration with real DDL — migration_run must apply it.
        file_put_contents(
            $this->appRoot . '/migrations/000001_create_gadget_table.sql',
            "CREATE TABLE IF NOT EXISTS gadget (id INTEGER PRIMARY KEY, label TEXT);\n"
        );

        // Real DB with real data, persisted to the file so each fromEnv() sees it.
        $db = Database::create('sqlite:///' . $this->dbFile);
        $db->execute('CREATE TABLE IF NOT EXISTS widget (id INTEGER PRIMARY KEY, name TEXT)');
        $db->execute("INSERT INTO widget (id, name) VALUES (1, 'alpha'), (2, 'beta')");
        // A dedicated no-primary-key seed target so seed_table inserts cleanly
        // (no PK collision with pre-existing rows).
        $db->execute('CREATE TABLE IF NOT EXISTS seed_target (label TEXT, amount INTEGER)');
        $db->commit();

        chdir($this->appRoot);

        // Bind the ORM to the throwaway DB so model-backed tools resolve it.
        \Tina4\ORM::bindDatabase(Database::create('sqlite:///' . $this->dbFile));

        // A real public route for route_test to drive through the real router.
        Router::get('/__conformance_hello', function ($request, $response) {
            return $response('hi');
        });

        // A real queued job so queue_status reports a real pending count.
        (new Queue(topic: 'default'))->push(['task' => 'conformance']);

        // A real tracked error so error_log returns real data (not a [] stub).
        // ErrorTracker lives in DevAdmin.php (not its own PSR-4 file); reference
        // DevAdmin so the autoloader loads that file and the class resolves.
        class_exists(\Tina4\DevAdmin::class);
        // clearAll() empties the in-memory store so this run starts clean without
        // touching the global error/exception handlers (reset() would pop them and
        // make the test "risky").
        ErrorTracker::clearAll();
        ErrorTracker::capture(
            'ConformanceProbeError',
            'boom from conformance test',
            "#0 conformance\n",
            __FILE__,
            __LINE__
        );

        // Real plans so plan_* tools have targets.
        $verify = Plan::create('conformance verify', 'prove the tools', ['step one', 'step two'], true);
        $archive = Plan::create('conformance archive', 'throwaway', ['x'], false);
        $this->verifyPlanName = $verify['name'] ?? 'conformance-verify.md';
        $this->archivePlanName = $archive['name'] ?? 'conformance-archive.md';
    }

    private string $verifyPlanName = '';
    private string $archivePlanName = '';

    protected function tearDown(): void
    {
        if ($this->oldCwd !== '') {
            chdir($this->oldCwd);
        }
        foreach ($this->savedEnv as $key => $prior) {
            if ($prior === null) {
                putenv($key);
                unset($_ENV[$key], $_SERVER[$key]);
            } else {
                putenv("{$key}={$prior}");
                $_ENV[$key] = $prior;
            }
        }
        ErrorTracker::clearAll();
        $this->rrmdir($this->appRoot);
    }

    private function setEnv(string $key, string $value): void
    {
        $this->savedEnv[$key] = getenv($key) === false ? null : getenv($key);
        putenv("{$key}={$value}");
        $_ENV[$key] = $value;
    }

    private function rrmdir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        foreach (scandir($dir) ?: [] as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $path = $dir . '/' . $entry;
            is_dir($path) ? $this->rrmdir($path) : @unlink($path);
        }
        @rmdir($dir);
    }

    /**
     * Safe, minimal args per tool so every write stays inside the sandbox and no
     * tool is starved of a required argument. Mirrors the invoke-every-tool sweep.
     *
     * @return array<string, array<string, mixed>>
     */
    private function toolArgs(): array
    {
        return [
            'database_query'     => ['sql' => 'SELECT id, name FROM widget ORDER BY id', 'params' => '[]'],
            'database_execute'   => ['sql' => "UPDATE widget SET name='updated' WHERE id=1", 'params' => '[]'],
            'database_tables'    => [],
            'database_columns'   => ['table' => 'widget'],
            'route_list'         => [],
            'route_test'         => ['method' => 'GET', 'path' => '/__conformance_hello'],
            'swagger_spec'       => [],
            'template_render'    => ['template' => 'Hello {{ name }}', 'data' => '{"name":"World"}'],
            'file_read'          => ['path' => 'composer.json'],
            'file_write'         => ['path' => 'src/routes/probe_generated.php', 'content' => "<?php\n// patched by probe\nreturn function () { return 'ok'; };\n"],
            'file_patch'         => ['path' => 'src/routes/probe_generated.php', 'old_string' => 'generated by probe', 'new_string' => 'patched by probe', 'count' => 1],
            'file_list'          => ['path' => 'src'],
            'asset_upload'       => ['filename' => 'probe.txt', 'content' => 'hello', 'encoding' => 'utf-8'],
            'migration_status'   => [],
            'migration_create'   => ['description' => 'add widget index'],
            'migration_run'      => [],
            'queue_status'       => ['topic' => 'default'],
            'session_list'       => [],
            'cache_stats'        => [],
            'orm_describe'       => [],
            'log_tail'           => ['lines' => 10],
            'error_log'          => ['limit' => 5],
            'env_list'           => [],
            'seed_table'         => ['table' => 'seed_target', 'count' => 3],
            'system_info'        => [],
            'plan_current'       => [],
            'plan_list'          => [],
            'plan_create'        => ['title' => 'tool created plan', 'goal' => 'g', 'steps' => ['a', 'b'], 'make_current' => false],
            'plan_switch_to'     => ['name' => $this->verifyPlanName],
            'plan_complete_step' => ['index' => 0],
            'plan_add_step'      => ['text' => 'a new step from probe'],
            'plan_note'          => ['text' => 'a breadcrumb note'],
            'plan_archive'       => ['name' => $this->archivePlanName],
            'plan_read'          => ['name' => $this->verifyPlanName],
            'plan_flesh'         => ['name' => $this->verifyPlanName],
            'docs_list'          => [],
            'docs_search'        => ['query' => 'queue', 'limit' => 3, 'context_lines' => 2],
            'docs_section'       => ['file' => 'composer.json', 'heading' => 'Auth'],
            'api_search'         => ['query' => 'Database', 'k' => 3, 'source' => 'all', 'include_private' => false],
            'api_class'          => ['name' => 'Router'],
            'api_method'         => ['class' => 'Router', 'name' => 'get'],
            'code_search'        => ['query' => 'widget', 'k' => 3, 'rebuild' => false],
            'git_status'         => [],
            'deps_list'          => [],
            'project_overview'   => [],
            'index_rebuild'      => [],
            'index_search'       => ['query' => 'widget', 'limit' => 10],
            'index_file'         => ['path' => 'src/orm/ConformanceWidget.php'],
            'index_overview'     => [],
        ];
    }

    /**
     * Boot the real dev-MCP server and invoke EVERY registered tool. Records each
     * result and asserts none threw — this alone catches the ArgumentCountError
     * throwers (migration_create/run) if a self-catch is removed.
     *
     * @return array<string, mixed> tool name => raw return value
     */
    private function invokeEveryTool(McpServer $server): array
    {
        $argMap = $this->toolArgs();
        $results = [];
        $threw = [];
        $missingArgs = [];

        foreach ($server->getToolList() as $tool) {
            $name = $tool['name'];
            if (!array_key_exists($name, $argMap)) {
                $missingArgs[] = $name;
            }
            try {
                $results[$name] = $server->callTool($name, $argMap[$name] ?? []);
            } catch (\Throwable $e) {
                $threw[$name] = get_class($e) . ': ' . $e->getMessage()
                    . ' @ ' . $e->getFile() . ':' . $e->getLine();
            }
        }

        $this->assertSame(
            [],
            $missingArgs,
            'New dev tool(s) with no args in the conformance map: ' . implode(', ', $missingArgs)
        );
        $this->assertSame(
            [],
            $threw,
            "Dev tool(s) threw an uncaught Throwable:\n" . implode("\n", array_map(
                fn($k, $v) => "  {$k} -> {$v}",
                array_keys($threw),
                array_values($threw)
            ))
        );

        return $results;
    }

    public function testEveryDevToolInvokesWithoutThrowing(): void
    {
        $server = new McpServer('/__dev/mcp', 'Tina4 Dev Tools');
        McpDevTools::register($server);

        // Registry is the source of truth — assert we actually enumerated the
        // whole toolkit (not a stale hardcoded subset).
        $names = array_column($server->getToolList(), 'name');
        $this->assertGreaterThanOrEqual(49, count($names), 'Dev toolkit shrank below 49 tools');
        $this->assertContains('migration_run', $names);
        $this->assertContains('database_execute', $names);

        $results = $this->invokeEveryTool($server);
        $this->assertNotEmpty($results);
    }

    /**
     * The 7 tools the sweep found broken must now return REAL success payloads:
     * not a stub info-string and not an {error} envelope.
     */
    public function testFixedToolsReturnRealPayloads(): void
    {
        $server = new McpServer('/__dev/mcp', 'Tina4 Dev Tools');
        McpDevTools::register($server);

        $r = $this->invokeEveryTool($server);

        // 1. migration_create — actually wrote a file on disk.
        $create = $r['migration_create'];
        $this->assertIsArray($create);
        $this->assertArrayNotHasKey('error', $create, 'migration_create returned {error}: ' . json_encode($create));
        $this->assertArrayHasKey('created', $create, 'migration_create did not report a created file: ' . json_encode($create));
        $this->assertFileExists($this->appRoot . '/migrations/' . $create['created']);

        // 2. migration_run — applied the real pending migration; the gadget table now exists.
        $run = $r['migration_run'];
        $this->assertIsArray($run);
        $this->assertArrayNotHasKey('error', $run, 'migration_run returned {error}: ' . json_encode($run));
        $this->assertArrayHasKey('applied', $run, 'migration_run did not return a migrate() result: ' . json_encode($run));
        $verifyDb = Database::create('sqlite:///' . $this->dbFile);
        $this->assertTrue($verifyDb->tableExists('gadget'), 'migration_run did not create the gadget table');

        // 3. route_test — dispatched the real route and returned a real response.
        $route = $r['route_test'];
        $this->assertIsArray($route);
        $this->assertArrayNotHasKey('error', $route, 'route_test returned {error}: ' . json_encode($route));
        $this->assertArrayNotHasKey('info', $route, 'route_test returned the old stub info-string: ' . json_encode($route));
        $this->assertSame(200, $route['status']);
        $this->assertStringContainsString('hi', $route['body']);
        $this->assertArrayHasKey('content_type', $route);

        // 4. seed_table — inserted N>0 real rows via the real seeder.
        $seed = $r['seed_table'];
        $this->assertIsArray($seed);
        $this->assertArrayNotHasKey('error', $seed, 'seed_table returned {error}: ' . json_encode($seed));
        $this->assertArrayNotHasKey('info', $seed, 'seed_table returned the old stub info-string: ' . json_encode($seed));
        // canonical cross-framework shape {table, inserted:<int>, failed:<int>}
        $this->assertArrayHasKey('inserted', $seed);
        $this->assertGreaterThan(0, $seed['inserted'], 'seed_table inserted no rows');
        $this->assertArrayHasKey('failed', $seed, 'seed_table missing the canonical failed count');
        $this->assertIsInt($seed['failed']);
        $seededCount = $verifyDb->fetch('SELECT COUNT(*) AS c FROM seed_target')->records[0]['c'];
        $this->assertGreaterThan(0, (int) $seededCount, 'seed_target has no rows after seed_table');

        // 5. error_log — returned the REAL tracked error (not the [] stub).
        $errors = $r['error_log'];
        $this->assertIsArray($errors);
        $this->assertNotEmpty($errors, 'error_log returned an empty list despite a captured error');
        $messages = array_column($errors, 'message');
        $this->assertContains('boom from conformance test', $messages, 'error_log did not surface the captured error: ' . json_encode($errors));

        // 6. queue_status — returned real counts (a job is pending).
        $queue = $r['queue_status'];
        $this->assertIsArray($queue);
        $this->assertArrayNotHasKey('error', $queue, 'queue_status returned {error}: ' . json_encode($queue));
        $this->assertSame('default', $queue['topic']);
        $this->assertGreaterThanOrEqual(1, $queue['pending'], 'queue_status did not see the pending job');

        // 7. database_execute — returned the TRUE affected-row count (was hardcoded 0).
        $exec = $r['database_execute'];
        $this->assertIsArray($exec);
        $this->assertArrayNotHasKey('error', $exec, 'database_execute returned {error}: ' . json_encode($exec));
        $this->assertTrue($exec['success']);
        $this->assertSame(1, $exec['affected_rows'], 'database_execute reported the wrong affected-row count: ' . json_encode($exec));
    }

    /**
     * migration_create refuses to spawn a duplicate for a slug that already
     * exists — it points the caller at the existing file instead (Python parity).
     */
    public function testMigrationCreateGuardsDuplicateSlug(): void
    {
        $server = new McpServer('/__dev/mcp', 'Tina4 Dev Tools');
        McpDevTools::register($server);

        $first = $server->callTool('migration_create', ['description' => 'create orders table']);
        $this->assertArrayHasKey('created', $first);

        $dup = $server->callTool('migration_create', ['description' => 'create orders table']);
        $this->assertIsArray($dup);
        $this->assertArrayHasKey('error', $dup, 'duplicate migration_create was not blocked: ' . json_encode($dup));
        $this->assertArrayHasKey('existing', $dup);
        $this->assertNotEmpty($dup['existing']);
    }
}
