# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 16 Sep 2021 10:57:23 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

clayton:$2y$10$e1gPRrSEKb2eF4vHHuUcpuqdIdEQZWCIeNGNpyy0pTbgPRAUAp7S2:Clayton Klassen:claytonklassen17@gmail.com:admin,user
