# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 16 Mar 2021 10:49:40 +0000
*               @ALL          1
*               @user         8
