<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: clayton
 * Date: Thu, 22 Jul 2021 17:06:37 +0200
 */

$conf['title'] = 'This is not a framework';
$conf['start'] = 'first-steps';
$conf['template'] = 'strap';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['target']['extern'] = 'target=_blank';
$conf['proxy']['user'] = 'barcovanrhijn@gmail.com';
$conf['proxy']['pass'] = '<b>XkIrdn0jUDI/eUVqS3A9by42Oz4uXDZOZ14oJVFbJkc2SCdpIzNjaVsnU2s0Z3k/byVVWCRGO0B5aH0/byJATlJ5VyNpWk55OQ==';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['lazyLoadingPlaceholderColor'] = '#fff';
$conf['tpl']['strap']['footerSlotPageName'] = 'slot_footer';
$conf['tpl']['strap']['headerSlotPageName'] = 'slot_header';
$conf['tpl']['strap']['sidekickSlotPageName'] = 'slot_sidekick';
