# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 16 Mar 2021 10:49:40 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

barco:$2y$10$HWnb2aCuZhqv9T7DD8b9LuD3MOu3xiAZwrJRyg9ffbmr.rdfs1g.O:Barco van Rhijn:barcovanrhijn@gmail.com:admin,user
andre:$2y$10$etnoaZCPSlPB3LiKh8NO1uWMImcblztlsKmoX2m4EM44ScBDeoYAO:Andre van Zuydam:andrevanzuydam@gmail.com:admin,user
cris:$2y$10$36qitjMy0WeZXcZf3pOMc.ldkLMrSat1cLd2g8K8wSI5LmLdqGDAC:Cris Higham:cris@justblink.co.za:admin,user
ronald:$2y$10$P5avRV3AFlDk5nps7F8FcuIWc00Ys9WyprD0TlYfv5veIHMQ8nw/.:Ronald Kyobe:kyoberonald@gmail.com:admin,user
clayton:$2y$10$FS96yWtNs4Wxta0t1jP11O4U/MYbFBnPCUwqxYIjCEtx5JlWg.Cj6:Clayton Klassen:claytonklassen17@gmail.com:admin,user
sidney:$2y$10$bWcQ4SE4g3QPiFlfIFdQouQY6pPKQPxIsaAAG0hC7sc0RRHJkcElS:Sidney Ramphalile:sidneyramphalile@gmail.com:admin,user
justin:$2y$10$7iqHFMZcun3EUH9rCAWx8OkK.XoRLs/.W7VpaF5h18uWe2AGTHwZ6:Justin Bruce:justin@codeinfinity.co.za:admin,user
